language: python

services:
  - docker

before_install:
- sudo apt-get install -y tree
- git submodule update --init --recursive
- docker pull uavcan/toxic:py35-py38

install:
- "echo $TRAVIS_BUILD_DIR"

script:
- "docker run --rm -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $TRAVIS_BUILD_DIR:/repo uavcan/toxic:py35-py38 /bin/sh -c tox"

after_success:
- tree
