/*
 *
 * UAVCAN data structure definition.                                                                          +-+ +-+
 *                                                                                                            | | | |
 * AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
 *                                                                                                              ---
 *                                                                                                               o
 * +------------------------------------------------------------------------------------------------------------------+
 *
 * Generator:
 * nunavut-0.2.4 (serialization was enabled)
 *
 *
 * Source File:
 * /Volumes/workspace/github32/nunavut/submodules/public_regulated_data_types/uavcan/time/TimeSystem.0.1.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-05-30 21:24:36.255390 UTC
 * Is deprecated: no
 * Fixed port ID: None
 * Full name:     uavcan.time.TimeSystem
 * Version:       0.1
 *
 */

#ifndef UAVCAN_TIME_TIME_SYSTEM_INCLUDED
#define UAVCAN_TIME_TIME_SYSTEM_INCLUDED

#include "nunavut/support/serialization.h"
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define UAVCAN_TIME_TIME_SYSTEM_0_1_MONOTONIC_SINCE_BOOT 0
#define UAVCAN_TIME_TIME_SYSTEM_0_1_TAI 1
#define UAVCAN_TIME_TIME_SYSTEM_0_1_APPLICATION_SPECIFIC 15

typedef struct
{
    uint8_t value;
} uavcan_time_TimeSystem_0_1;

/**
 * Initialize an uavcan_time_TimeSystem_0_1 instance to default values.
 * No memory is allocated within this method.
 *
 * @param out_instance A structure instance to Initialize.
 */
inline void uavcan_time_time_system_0_1_init(uavcan_time_TimeSystem_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->value = 0;
        /* Ignoring 4 padding bit(s). */
    }
}
/* TODO: issue #112, add serialization support for C types. */

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_TIME_TIME_SYSTEM */
