steps:
  - label: ':python::hammer: tox build, test, and report'
    if: build.branch == "master" && pipeline.slug == "nunavut-release"
    id: toxic-docker-build
    command: "tox"
    artifact_paths:
      - ".tox/report/tmp/*"
      - ".tox/mypy/tmp/*"
      - ".tox/flake8/tmp/*"
      - ".tox/dist/*.zip"
      - ".tox/py*-test/tmp/xunit-result.xml"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/toxic:py35-py38-sq"
          propagate-environment: true
          environment:
            - "SONARQUBE_TOKEN"
            - "PYPI_PASSWORD"
            - "BUILDKITE"
            - "BUILDKITE_BUILD_NUMBER"
    agents:
      queue: 'default'
    timeout_in_minutes: 40
  - label: ':cpp::hammer: verification build, c, gcc'
    if: build.branch == "master" && pipeline.slug == "nunavut-release"
    id: c-gcc-docker-verify
    command: "./.buildkite/verify_c.sh"
    artifact_paths:
      - "verification/build_c/coverage_all.zip"
      - "verification/build_cpp/coverage_all.zip"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/c_cpp:ubuntu-18.04"
          propagate-environment: true
          environment:
            - "BUILDKITE"
            - "BUILDKITE_BUILD_NUMBER"
    agents:
      queue: 'default'
  - label: ':cpp::hammer: verification build, cpp, gcc'
    if: build.branch == "master" && pipeline.slug == "nunavut-release"
    id: cpp-gcc-docker-verify
    command: "./.buildkite/verify.py -l cpp -f"
    artifact_paths:
      - "verification/build_c/coverage_all.zip"
      - "verification/build_cpp/coverage_all.zip"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/c_cpp:ubuntu-18.04"
          propagate-environment: true
          environment:
            - "BUILDKITE"
            - "BUILDKITE_BUILD_NUMBER"
    agents:
      queue: 'default'
  - wait
  - label: ':python::amazon-s3::sonarqube: release'
    if: build.branch == "master" && pipeline.slug == "nunavut-release"
    id: toxic-docker-release
    command: "./.buildkite/release.sh"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/toxic:py35-py38-sq"
          propagate-environment: true
          environment:
            - "SONARQUBE_TOKEN"
            - "PYPI_PASSWORD"
            - "BUILDKITE"
            - "BUILDKITE_BUILD_NUMBER"
    agents:
      queue: 'default'
    timeout_in_minutes: 15
