nunavut.lang.cpp:
  options:
    variable_array_type_include: <cetl/variable_length_array.hpp>
    variable_array_type_template: "cetl::VariableLengthArray<{TYPE}, typename std::allocator_traits<Allocator>::template rebind_alloc<{TYPE}>>"
    variable_array_type_init_args_template: "{SIZE}"
    variable_array_type_allocator_type: "cetl::pf17::pmr::polymorphic_allocator"
